# Generated by Django 5.1.6 on 2025-03-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('website', models.URLField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='WatchList',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='name',
            new_name='titile',
        ),
    ]
